env: "local" # local, dev, prod
storage_path: "postgres://postgres:Raider66@localhost:5432/postgres"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
  user: "my_user"
  password: "my_pass"